/*
 * Automatically generated by SheenFigureGenerator tool. 
 * DO NOT EDIT!!
 */

#ifndef _SF_GENERAL_CATEGORY_LOOKUP_H
#define _SF_GENERAL_CATEGORY_LOOKUP_H

#include <SFConfig.h>
#include <SFTypes.h>

#include "SFGeneralCategory.h"

SF_INTERNAL SFGeneralCategory SFGeneralCategoryDetermine(SFCodepoint codepoint);

#endif
