/*
 * Automatically generated by SheenFigureGenerator tool. 
 * DO NOT EDIT!!
 */

#include <SFConfig.h>

#include "SFBase.h"
#include "SFJoiningType.h"
#include "SFJoiningTypeLookup.h"

#define BYTE(l, h)  \
(SFUInt8)           \
(                   \
   ((l & 0xF) << 4) \
 | ((h & 0xF) << 0) \
)

#define C     SFJoiningTypeC
#define D     SFJoiningTypeD
#define F     SFJoiningTypeF
#define L     SFJoiningTypeL
#define R     SFJoiningTypeR
#define U     SFJoiningTypeU

static const SFUInt8 _SFJoiningTypeData[] = {
#define _SFJoiningTypeData_0000 0x0000
    BYTE(U, U), BYTE(U, U), BYTE(U, U), BYTE(F, F), BYTE(U, F), BYTE(F, U), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(D, U), BYTE(R, R), BYTE(R, R), BYTE(D, R), BYTE(D, R), BYTE(D, D), BYTE(D, D), BYTE(D, R),
    BYTE(R, R), BYTE(R, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(C, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(R, D), BYTE(D, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(D, D),
    BYTE(F, R), BYTE(R, R), BYTE(U, R), BYTE(R, R), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, R),
    BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(R, D), BYTE(D, R), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(D, R), BYTE(D, R),
    BYTE(D, D), BYTE(R, R), BYTE(F, R), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, U), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(R, R),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(D, D), BYTE(D, F), BYTE(F, D),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(R, F), BYTE(D, D), BYTE(D, R), BYTE(R, R), BYTE(R, R), BYTE(D, D), BYTE(D, D), BYTE(R, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(R, D), BYTE(R, D), BYTE(R, D), BYTE(D, R),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, R), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(R, R), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(R, D), BYTE(D, D),
    BYTE(D, R), BYTE(D, R), BYTE(R, D), BYTE(D, D), BYTE(R, R), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(C, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(R, D), BYTE(D, D), BYTE(D, D), BYTE(R, R), BYTE(D, R), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(R, D), BYTE(U, U), BYTE(U, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(R, R), BYTE(R, U), BYTE(R, D),
    BYTE(D, R), BYTE(R, D), BYTE(D, F),
#define _SFJoiningTypeData_015B 0x015B
    BYTE(U, D), BYTE(F, F), BYTE(C, F), BYTE(F, F), BYTE(U, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(U, U), BYTE(U, U), BYTE(U, U),
    BYTE(U, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, F), BYTE(D, F),
#define _SFJoiningTypeData_01AE 0x01AE
    BYTE(U, C), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(U, U), BYTE(U, U),
#define _SFJoiningTypeData_01DD 0x01DD
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(L, U),
#define _SFJoiningTypeData_01F7 0x01F7
    BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(U, R), BYTE(U, R), BYTE(R, U), BYTE(U, L), BYTE(R, R),
    BYTE(R, R), BYTE(R, D), BYTE(D, D), BYTE(D, L), BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(D, D),
    BYTE(D, R), BYTE(U, U), BYTE(R, F), BYTE(F, F), BYTE(F, F), BYTE(F, D), BYTE(D, D), BYTE(D, R),
#define _SFJoiningTypeData_020F 0x020F
    BYTE(D, R), BYTE(D, R), BYTE(R, R), BYTE(D, D), BYTE(D, R), BYTE(D, D), BYTE(R, D), BYTE(R, R),
    BYTE(D, R), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, R), BYTE(R, R), BYTE(R, D), BYTE(D, U)
};

SF_INTERNAL SFJoiningType SFJoiningTypeDetermine(SFCodepoint codepoint) {
    SFUInteger diff;
    SFUInteger block;
    SFUInt8 value;

    if (codepoint < 0xA840) {
        if (codepoint < 0x1806) {
            if (codepoint < 0x0600) {
                goto NotFound;
            } else if (codepoint > 0x08B4) {
                goto NotFound;
            } else {
                diff = codepoint - 0x0600;
                block = _SFJoiningTypeData_0000 * 2;
            }
        } else if (codepoint > 0x18AA) {
            if (codepoint < 0x200C) {
                goto NotFound;
            } else if (codepoint > 0x2069) {
                goto NotFound;
            } else {
                diff = codepoint - 0x200C;
                block = _SFJoiningTypeData_01AE * 2;
            }
        } else {
            diff = codepoint - 0x1806;
            block = _SFJoiningTypeData_015B * 2;
        }
    } else if (codepoint > 0xA873) {
        if (codepoint < 0x10B80) {
            if (codepoint < 0x10AC0) {
                goto NotFound;
            } else if (codepoint > 0x10AEF) {
                goto NotFound;
            } else {
                diff = codepoint - 0x10AC0;
                block = _SFJoiningTypeData_01F7 * 2;
            }
        } else if (codepoint > 0x10BAF) {
            goto NotFound;
        } else {
            diff = codepoint - 0x10B80;
            block = _SFJoiningTypeData_020F * 2;
        }
    } else {
        diff = codepoint - 0xA840;
        block = _SFJoiningTypeData_01DD * 2;
    }

    value = _SFJoiningTypeData[(block + diff) >> 1];

    if (diff & 1) {
        return (SFJoiningType)(value & 0xF);
    }

    return (SFJoiningType)(value >> 4);

NotFound:
    return SFJoiningTypeF;
}

#undef BYTE
#undef C
#undef D
#undef F
#undef L
#undef R
#undef U
