/*
 * Automatically generated by SheenFigureGenerator tool. 
 * DO NOT EDIT!!
 */

#ifndef _SF_JOINING_TYPE_LOOKUP_H
#define _SF_JOINING_TYPE_LOOKUP_H

#include <SFConfig.h>

#include "SFBase.h"
#include "SFJoiningType.h"

SF_INTERNAL SFJoiningType SFJoiningTypeDetermine(SFCodepoint codepoint);

#endif
