/*
 * Automatically generated by SheenFigureGenerator tool. 
 * DO NOT EDIT!!
 */

#include <SFConfig.h>
#include <SFTypes.h>

#include "SFJoiningType.h"
#include "SFJoiningTypeLookup.h"

#define BYTE(l, h)  \
(SFUInt8)           \
(                   \
   ((l & 0xF) << 4) \
 | ((h & 0xF) << 0) \
)

#define C     SFJoiningTypeC
#define D     SFJoiningTypeD
#define F     SFJoiningTypeF
#define L     SFJoiningTypeL
#define R     SFJoiningTypeR
#define U     SFJoiningTypeU

static const SFUInt8 _SFJoiningTypeData[] = {
    BYTE(U, U), BYTE(U, U), BYTE(U, F), BYTE(F, U), BYTE(F, F), BYTE(U, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, D),
    BYTE(U, R), BYTE(R, R), BYTE(R, D), BYTE(R, D), BYTE(R, D), BYTE(D, D), BYTE(D, D), BYTE(R, R),
    BYTE(R, R), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, C),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(D, D), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, D), BYTE(D, F),
    BYTE(R, R), BYTE(R, U), BYTE(R, R), BYTE(R, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, R),
    BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, R),
    BYTE(D, D), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, D), BYTE(R, D), BYTE(R, D),
    BYTE(D, R), BYTE(R, F), BYTE(R, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(U, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, R), BYTE(R, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, D), BYTE(D, D), BYTE(F, F), BYTE(D, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, R),
    BYTE(F, D), BYTE(D, D), BYTE(R, R), BYTE(R, R), BYTE(R, D), BYTE(D, D), BYTE(D, R), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(D, R), BYTE(D, R), BYTE(D, D), BYTE(R, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(R, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(R, R), BYTE(R, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(R, R), BYTE(D, D), BYTE(D, D),
    BYTE(R, D), BYTE(R, R), BYTE(D, D), BYTE(D, R), BYTE(R, D), BYTE(D, D), BYTE(D, D), BYTE(D, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, C), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, R),
    BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(R, D), BYTE(R, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, R), BYTE(D, U), BYTE(U, U), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(R, R), BYTE(U, R), BYTE(D, D),
    BYTE(R, R), BYTE(D, D),
#define _SFJoiningTypeData_015A
    BYTE(U, D), BYTE(F, F), BYTE(C, F), BYTE(F, F), BYTE(U, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(U, U), BYTE(U, U), BYTE(U, U),
    BYTE(U, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, F), BYTE(D, F),
#define _SFJoiningTypeData_01AD
    BYTE(U, C), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(U, U), BYTE(U, U),
#define _SFJoiningTypeData_01DC
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(L, U),
#define _SFJoiningTypeData_01F6
    BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(U, R), BYTE(U, R), BYTE(R, U), BYTE(U, L), BYTE(R, R),
    BYTE(R, R), BYTE(R, D), BYTE(D, D), BYTE(D, L), BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(D, D),
    BYTE(D, R), BYTE(U, U), BYTE(R, F), BYTE(F, F), BYTE(F, F), BYTE(F, D), BYTE(D, D), BYTE(D, R),
#define _SFJoiningTypeData_020E
    BYTE(D, R), BYTE(D, R), BYTE(R, R), BYTE(D, D), BYTE(D, R), BYTE(D, D), BYTE(R, D), BYTE(R, R),
    BYTE(D, R), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, R), BYTE(R, R), BYTE(R, D), BYTE(D, F)
};

SF_INTERNAL SFJoiningType SFJoiningTypeDetermine(SFCodepoint codepoint) {
    SFUInteger diff;
    SFUInteger block;
    SFUInt8 value;

    if (codepoint <= 0x2069) {
        if (codepoint <= 0x08B4) {
            diff = 0x08B4 - codepoint;
            block = 0x015A;
        } else {
            if (codepoint <= 0x18AA) {
                diff = 0x18AA - codepoint;
                block = 0x01AD;
            } else {
                diff = 0x18AA - codepoint;
                block = 0x01DC;
            }
        }
    } else {
        if (codepoint <= 0xA873) {
            diff = 0xA873 - codepoint;
            block = 0x01F6;
        } else {
            if (codepoint <= 0x10AEF) {
                diff = 0x10AEF - codepoint;
                block = 0x020E;
            } else {
                diff = 0x10AEF - codepoint;
                block = 0x0226;
            }
        }
    }

    value = _SFJoiningTypeData[block - (diff >> 1)];

    if (diff & 1) {
        return (SFJoiningType)(value & 0xF);
    }

    return (SFJoiningType)(value >> 4);
}

#undef BYTE
#undef C
#undef D
#undef F
#undef L
#undef R
#undef U
