/*
 * Automatically generated by SheenFigureGenerator tool. 
 * DO NOT EDIT!!
 *
 * REQUIRED MEMORY: 608 Bytes
 */

#include <SFConfig.h>

#include "SFBase.h"
#include "SFJoiningType.h"
#include "SFJoiningTypeLookup.h"

#define BYTE(l, h)  \
(SFUInt8)           \
(                   \
   ((l & 0xF) << 4) \
 | ((h & 0xF) << 0) \
)

#define IN_RANGE(c, l, h)        \
(                                \
 (SFCodepoint)(c - l) <= (h - l) \
)

#define C     SFJoiningTypeC
#define D     SFJoiningTypeD
#define F     SFJoiningTypeF
#define L     SFJoiningTypeL
#define R     SFJoiningTypeR
#define T     SFJoiningTypeT
#define U     SFJoiningTypeU

static const SFUInt8 _SFJoiningTypeData[608] = {
#define JOINING_BLOCK_0600 0x0000
    BYTE(U, U), BYTE(U, U), BYTE(U, U), BYTE(F, F), BYTE(U, F), BYTE(F, U), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(D, U), BYTE(R, R), BYTE(R, R), BYTE(D, R), BYTE(D, R), BYTE(D, D), BYTE(D, D), BYTE(D, R),
    BYTE(R, R), BYTE(R, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(C, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(R, D), BYTE(D, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(D, D),
    BYTE(F, R), BYTE(R, R), BYTE(U, R), BYTE(R, R), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, R),
    BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(R, D), BYTE(D, R), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(R, R), BYTE(D, R), BYTE(D, R),
    BYTE(D, D), BYTE(R, R), BYTE(F, R), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, U), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(R, R),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(D, D), BYTE(D, F), BYTE(F, D),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(R, F), BYTE(D, D), BYTE(D, R), BYTE(R, R), BYTE(R, R), BYTE(D, D), BYTE(D, D), BYTE(R, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(R, D), BYTE(R, D), BYTE(R, D), BYTE(D, R),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, R), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(R, R), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(R, D), BYTE(D, D),
    BYTE(D, R), BYTE(D, R), BYTE(R, D), BYTE(D, D), BYTE(R, R), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(C, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(R, D), BYTE(D, D), BYTE(D, D), BYTE(R, R), BYTE(D, R), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(R, D), BYTE(U, U), BYTE(U, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(R, R), BYTE(R, U), BYTE(R, D),
    BYTE(D, R), BYTE(R, D), BYTE(D, F), BYTE(D, D), BYTE(D, R), BYTE(D, D), BYTE(D, D), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(U, F),
#define JOINING_BLOCK_1806 0x0172
    BYTE(U, D), BYTE(F, F), BYTE(C, F), BYTE(F, F), BYTE(U, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(U, U), BYTE(U, U), BYTE(U, T),
    BYTE(T, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, F), BYTE(D, F),
#define JOINING_BLOCK_200C 0x01C5
    BYTE(U, C), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, U), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(U, U), BYTE(U, U),
#define JOINING_BLOCK_A840 0x01F4
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(L, U),
#define JOINING_BLOCK_10AC0 0x020E
    BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(U, R), BYTE(U, R), BYTE(R, U), BYTE(U, L), BYTE(R, R),
    BYTE(R, R), BYTE(R, D), BYTE(D, D), BYTE(D, L), BYTE(D, D), BYTE(D, D), BYTE(D, R), BYTE(D, D),
    BYTE(D, R), BYTE(U, U), BYTE(R, F), BYTE(F, F), BYTE(F, F), BYTE(F, D), BYTE(D, D), BYTE(D, R),
#define JOINING_BLOCK_10B80 0x0226
    BYTE(D, R), BYTE(D, R), BYTE(R, R), BYTE(D, D), BYTE(D, R), BYTE(D, D), BYTE(R, D), BYTE(R, R),
    BYTE(D, R), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F),
    BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, F), BYTE(F, R), BYTE(R, R), BYTE(R, D), BYTE(D, U),
#define JOINING_BLOCK_1E900 0x023E
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D), BYTE(D, D),
    BYTE(D, D), BYTE(D, D)
};

SF_INTERNAL SFJoiningType SFJoiningTypeDetermine(SFCodepoint codepoint) {
    SFUInteger offset = SFInvalidIndex;
    SFUInteger block;

    switch (codepoint >> 12) {
        case 0x0:
            if (IN_RANGE(codepoint, 0x0600, 0x08E2)) {
                offset = codepoint - 0x0600;
                block = JOINING_BLOCK_0600;
            }
            break;

        case 0x1:
            if (IN_RANGE(codepoint, 0x1806, 0x18AA)) {
                offset = codepoint - 0x1806;
                block = JOINING_BLOCK_1806;
            }
            break;

        case 0x2:
            if (IN_RANGE(codepoint, 0x200C, 0x2069)) {
                offset = codepoint - 0x200C;
                block = JOINING_BLOCK_200C;
            }
            break;

        default:
            if (IN_RANGE(codepoint, 0xA840, 0xA873)) {
                offset = codepoint - 0xA840;
                block = JOINING_BLOCK_A840;
            } else if (IN_RANGE(codepoint, 0x10AC0, 0x10AEF)) {
                offset = codepoint - 0x10AC0;
                block = JOINING_BLOCK_10AC0;
            } else if (IN_RANGE(codepoint, 0x10B80, 0x10BAF)) {
                offset = codepoint - 0x10B80;
                block = JOINING_BLOCK_10B80;
            } else if (IN_RANGE(codepoint, 0x1E900, 0x1E943)) {
                offset = codepoint - 0x1E900;
                block = JOINING_BLOCK_1E900;
            }
            break;

    }

    if (offset != SFInvalidIndex) {
        SFUInt8 value = _SFJoiningTypeData[block + (offset >> 1)];

        if (offset & 1) {
            return (SFJoiningType)(value & 0xF);
        }

        return (SFJoiningType)(value >> 4);
    }

    return SFJoiningTypeF;
}

#undef BYTE
#undef IN_RANGE
#undef C
#undef D
#undef F
#undef L
#undef R
#undef T
#undef U
